
# Add 'repo' label to any root file changes
repo:
- '*'
# 
git:
- any: ['**/.gitignore']
#
workflow:
- any: ['.github/**/*']
#
project:
- any: ['actions.yml', 'node/package.json']
#
code:
- any: ['node/**/*']
#
documentation:
- any: ['**/*.md']

...
# EOF